import {labels,reportLabels,type Profile} from './model.ts';
import type {History} from './history.ts';
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
const number=(v:number|null)=>v===null?'—':new Intl.NumberFormat('en-US',{maximumFractionDigits:1}).format(v);
export const chartSummaryCss=`.series-summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px;margin:4px 0 20px}.series-summary span{display:block;font-size:.75rem;margin-bottom:6px}.series-summary strong{font-size:1.5rem;font-variant-numeric:tabular-nums;overflow-wrap:anywhere}.series .gridline{stroke:#544267;stroke-dasharray:3 4;fill:none}@media(max-width:420px){.series-summary{gap:8px}.series-summary strong{font-size:1.1rem}}`;
export const views=['cards','graph','carousel','ticker'] as const;
export type View=typeof views[number];
export const view=(value:string|null):View=>views.includes(value as View)?value as View:'cards';

export function graph(data:History):string {
  const title=labels[data.metric]||reportLabels[data.metric]||data.metric;
  const grouped=new Map<string,History['points']>();
  for(const p of data.points){const key=JSON.stringify([p.scope,p.sourceKind,p.sourceUrl,p.precision,p.sampleSize]);grouped.set(key,[...(grouped.get(key)||[]),p]);}
  return `<section class="trend" aria-label="${esc(title)} history"><h3>${esc(title)} · ${data.days}-day history</h3><p class="muted">${esc(data.note)}</p>${!data.points.length?'<p>No recorded observations yet. A trend appears as real observations arrive; no historical values are generated.</p>':''}${[...grouped.values()].slice(0,8).map(points=>{
    points.sort((a,b)=>Date.parse(a.observedAt)-Date.parse(b.observedAt));
    const low=Math.min(...points.map(p=>p.value)),high=Math.max(...points.map(p=>p.value)),padding=Math.max(1,(high-low)*.15);
    const floor=Math.max(0,Math.floor(low-padding)),ceiling=Math.ceil(high+padding),range=ceiling-floor;
    const first=Date.parse(points[0].observedAt),last=Date.parse(points.at(-1)!.observedAt),span=last-first||86400000;
    const coords=points.map(p=>({x:80+(Date.parse(p.observedAt)-first)/span*550,y:180-(p.value-floor)/range*145,p}));
    const segments:string[]=[];let segment:string[]=[];
    coords.forEach((c,i)=>{if(i&&Date.parse(c.p.observedAt)-Date.parse(coords[i-1].p.observedAt)>(data.resolution==='hour'?2*3600000:2*86400000)){segments.push(segment.join(' '));segment=[];}segment.push(`${c.x.toFixed(2)},${c.y.toFixed(2)}`);});segments.push(segment.join(' '));
    return `<div class="series"><div class="series-summary"><div><span>Latest observed</span><strong>${number(points.at(-1)!.value)}</strong></div><div><span>First in range</span><strong>${number(points[0].value)}</strong></div><div><span>Observations</span><strong>${points.length}</strong></div></div><p>${esc(points[0].scope)} · ${esc(points[0].precision)} · <a href="${esc(points[0].sourceUrl)}">${esc(points[0].sourceKind.replaceAll('_',' '))}</a></p><svg viewBox="0 0 680 220" role="img" aria-label="${esc(title)}: ${points.length} recorded observations, latest ${number(points.at(-1)!.value)}; axis ${number(floor)} to ${number(ceiling)}">${[floor,(floor+ceiling)/2,ceiling].map(t=>{const y=180-(t-floor)/range*145;return `<path d="M80 ${y}H640" class="gridline"/><text x="68" y="${y+4}" text-anchor="end">${number(t)}</text>`;}).join('')}<text x="80" y="210">${esc(points[0].observedAt.slice(0,data.resolution==='hour'?16:10).replace('T',' '))}</text><text x="640" y="210" text-anchor="end">${esc(points.at(-1)!.observedAt.slice(0,data.resolution==='hour'?16:10).replace('T',' '))}</text>${segments.filter(s=>s.includes(' ')).map(s=>`<polyline points="${s}"/>`).join('')}${coords.map(c=>`<circle cx="${c.x.toFixed(2)}" cy="${c.y.toFixed(2)}" r="4"><title>${esc(c.p.observedAt)}: ${number(c.p.value)}</title></circle>`).join('')}</svg><p class="muted">Y-axis: ${number(floor)}–${number(ceiling)}${floor>0?' (not zero-based)':''}. Gaps longer than two ${data.resolution==='hour'?'hours':'days'} are not connected. Sample sizes and sources are kept separate.</p>${points.length===1?'<p class="muted">One observation recorded. Not enough history to calculate a trend.</p>':''}</div>`;
  }).join('')}${grouped.size>8?'<p>Eight measurement series shown; all observations remain in the data table and JSON.</p>':''}${data.points.length?`<details><summary>Accessible data table · ${data.points.length} observations</summary><div class="table-scroll" tabindex="0" role="region" aria-label="History table"><table><caption>${esc(title)}: actual observations</caption><thead><tr><th scope="col">Observed (UTC)</th><th scope="col">Value</th><th scope="col">Scope / precision</th><th scope="col">Source</th></tr></thead><tbody>${data.points.map(p=>`<tr><td><time datetime="${esc(p.observedAt)}">${esc(p.observedAt)}</time></td><td>${number(p.value)}</td><td>${esc(p.scope)} · ${esc(p.precision)}${p.sampleSize!==null?` · sample ${p.sampleSize}`:''}</td><td><a href="${esc(p.sourceUrl)}">${esc(p.sourceKind.replaceAll('_',' '))}</a></td></tr>`).join('')}</tbody></table></div></details>`:''}</section>`;
}

export function motion(profile:Profile,mode:'carousel'|'ticker'):string {
 const metrics=Object.entries(profile.metrics).sort((a,b)=>Number(b[1].value!==null)-Number(a[1].value!==null));
 return `<section class="motion-display" data-motion="${mode}" aria-label="${mode==='carousel'?'Rotating metric cards':'Metric ticker'}"><div class="motion-controls" hidden><button type="button" data-previous>Previous</button><button type="button" data-toggle aria-pressed="false">Play ${mode}</button><button type="button" data-next>Next</button><span data-position aria-live="polite"></span></div><div class="motion-track" tabindex="0" role="region" aria-label="Metric cards"><dl class="motion-items">${metrics.map(([key,m])=>`<div class="metric"><dt>${esc(labels[key]||reportLabels[key]||key)}</dt><dd>${number(m.value)}<p>${esc(m.scope)}</p><p>${m.observedAt?`${m.current?'Observed':'Older snapshot'} ${esc(m.observedAt)}`:'No observation available'}</p><p>${esc(m.precision)} · ${esc(m.source.kind.replaceAll('_',' '))}</p></dd></div>`).join('')}</dl></div><p class="muted">Playback is opt-in. Reduced-motion preferences disable automatic rotation. Counts keep their original dates.</p></section>`;
}
export const viewCss=`.trend,.motion-display{margin:24px 0;border-top:1px solid #544267;padding-top:16px}.series{background:#21182e;padding:16px;border-radius:10px;margin:16px 0}.series p{font-size:.8rem;overflow-wrap:anywhere}.series svg{display:block;width:100%;height:auto;max-height:260px;overflow:visible}.series svg text{fill:#d9c9ed;font:12px system-ui}.series svg .axis{stroke:#76648e;fill:none}.series polyline{fill:none;stroke:#c194ff;stroke-width:3}.series circle{fill:#eedbff;stroke:#21182e;stroke-width:2}.table-scroll{overflow-x:auto}table{border-collapse:collapse;font-size:.8rem;width:100%}th,td{text-align:left;padding:10px;border-bottom:1px solid #584766}summary{cursor:pointer;padding:12px}.motion-controls{display:flex;flex-wrap:wrap;gap:8px;align-items:center}.motion-controls button{width:auto;min-height:44px}.motion-track{overflow-x:auto;max-width:100%;scroll-snap-type:x mandatory}.motion-items{display:flex;gap:12px;margin:16px 0}.motion-items .metric{flex:0 0 min(100%,270px);scroll-snap-align:start}.motion-display[data-ready=carousel] .motion-items{display:block}.motion-display[data-ready=carousel] .metric{max-width:100%}[hidden]{display:none!important}.view-options{display:flex;flex-wrap:wrap;gap:12px}.view-options a{padding:8px 14px;border:1px solid #695381;border-radius:8px}.view-form{grid-template-columns:repeat(3,minmax(0,1fr))}.view-form button{align-self:end}@media(max-width:680px){.view-form{grid-template-columns:1fr}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important}}`;
export const motionScript=`(()=>{for(const panel of document.querySelectorAll('[data-motion]')){const controls=panel.querySelector('.motion-controls'),items=[...panel.querySelectorAll('.metric')],toggle=panel.querySelector('[data-toggle]'),position=panel.querySelector('[data-position]'),track=panel.querySelector('.motion-track');if(!items.length)continue;const reduced=matchMedia('(prefers-reduced-motion: reduce)');let index=0,timer=null;const mode=panel.dataset.motion;panel.dataset.ready=mode;controls.hidden=false;function show(){items.forEach((item,i)=>{item.hidden=mode==='carousel'&&i!==index});if(mode==='ticker')track.scrollTo({left:items[index].offsetLeft-items[0].offsetLeft,behavior:'auto'});position.textContent=(index+1)+' of '+items.length;}function stop(){clearInterval(timer);timer=null;toggle.textContent='Play '+mode;toggle.setAttribute('aria-pressed','false');}function step(delta){index=(index+delta+items.length)%items.length;show();}panel.querySelector('[data-next]').addEventListener('click',()=>{stop();step(1)});panel.querySelector('[data-previous]').addEventListener('click',()=>{stop();step(-1)});toggle.addEventListener('click',()=>{if(timer){stop();return}if(reduced.matches)return;toggle.textContent='Pause '+mode;toggle.setAttribute('aria-pressed','true');timer=setInterval(()=>{if(!document.hidden)step(1)},6000)});panel.addEventListener('focusin',e=>{if(e.target!==toggle)stop()});document.addEventListener('visibilitychange',()=>{if(document.hidden)stop()});reduced.addEventListener('change',()=>{stop();toggle.disabled=reduced.matches});toggle.disabled=reduced.matches;show();}})();`;
